require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecurringBillsController do

  # This should return the minimal set of attributes required to create a valid
  # RecurringBill. As you add validations to RecurringBill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "uid" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecurringBillsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recurring_bills as @recurring_bills" do
      recurring_bill = RecurringBill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recurring_bills).should eq([recurring_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested recurring_bill as @recurring_bill" do
      recurring_bill = RecurringBill.create! valid_attributes
      get :show, {:id => recurring_bill.to_param}, valid_session
      assigns(:recurring_bill).should eq(recurring_bill)
    end
  end

  describe "GET new" do
    it "assigns a new recurring_bill as @recurring_bill" do
      get :new, {}, valid_session
      assigns(:recurring_bill).should be_a_new(RecurringBill)
    end
  end

  describe "GET edit" do
    it "assigns the requested recurring_bill as @recurring_bill" do
      recurring_bill = RecurringBill.create! valid_attributes
      get :edit, {:id => recurring_bill.to_param}, valid_session
      assigns(:recurring_bill).should eq(recurring_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecurringBill" do
        expect {
          post :create, {:recurring_bill => valid_attributes}, valid_session
        }.to change(RecurringBill, :count).by(1)
      end

      it "assigns a newly created recurring_bill as @recurring_bill" do
        post :create, {:recurring_bill => valid_attributes}, valid_session
        assigns(:recurring_bill).should be_a(RecurringBill)
        assigns(:recurring_bill).should be_persisted
      end

      it "redirects to the created recurring_bill" do
        post :create, {:recurring_bill => valid_attributes}, valid_session
        response.should redirect_to(RecurringBill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recurring_bill as @recurring_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringBill.any_instance.stub(:save).and_return(false)
        post :create, {:recurring_bill => { "uid" => "invalid value" }}, valid_session
        assigns(:recurring_bill).should be_a_new(RecurringBill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringBill.any_instance.stub(:save).and_return(false)
        post :create, {:recurring_bill => { "uid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recurring_bill" do
        recurring_bill = RecurringBill.create! valid_attributes
        # Assuming there are no other recurring_bills in the database, this
        # specifies that the RecurringBill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecurringBill.any_instance.should_receive(:update_attributes).with({ "uid" => "MyString" })
        put :update, {:id => recurring_bill.to_param, :recurring_bill => { "uid" => "MyString" }}, valid_session
      end

      it "assigns the requested recurring_bill as @recurring_bill" do
        recurring_bill = RecurringBill.create! valid_attributes
        put :update, {:id => recurring_bill.to_param, :recurring_bill => valid_attributes}, valid_session
        assigns(:recurring_bill).should eq(recurring_bill)
      end

      it "redirects to the recurring_bill" do
        recurring_bill = RecurringBill.create! valid_attributes
        put :update, {:id => recurring_bill.to_param, :recurring_bill => valid_attributes}, valid_session
        response.should redirect_to(recurring_bill)
      end
    end

    describe "with invalid params" do
      it "assigns the recurring_bill as @recurring_bill" do
        recurring_bill = RecurringBill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringBill.any_instance.stub(:save).and_return(false)
        put :update, {:id => recurring_bill.to_param, :recurring_bill => { "uid" => "invalid value" }}, valid_session
        assigns(:recurring_bill).should eq(recurring_bill)
      end

      it "re-renders the 'edit' template" do
        recurring_bill = RecurringBill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringBill.any_instance.stub(:save).and_return(false)
        put :update, {:id => recurring_bill.to_param, :recurring_bill => { "uid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recurring_bill" do
      recurring_bill = RecurringBill.create! valid_attributes
      expect {
        delete :destroy, {:id => recurring_bill.to_param}, valid_session
      }.to change(RecurringBill, :count).by(-1)
    end

    it "redirects to the recurring_bills list" do
      recurring_bill = RecurringBill.create! valid_attributes
      delete :destroy, {:id => recurring_bill.to_param}, valid_session
      response.should redirect_to(recurring_bills_url)
    end
  end

end
